name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: root
      DB_PORT: 5432
    strategy:
      matrix:
        go_version: ['1.18', '>=1.18']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Build
      run: go build main.go
    
    - name: Build-DB
      run: docker compose build
      
    - name: Create-DB
      run: docker compose up -d

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Build
      run: go build -v main.go
      
    - name: Create container image
      uses: docker/build-push-action@v6.15.0
      with:
        pull: true
        tag: 'curso_ci_2:latest'
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        path: curso_ci_2:latest
